version: "3.8"

services:
  jenkins:
    build: .
    container_name: jenkins
    user: "1000:1000"
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
